name: Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libapt-pkg-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - name: Setup rubocop
        run: |
          bundle install --with=rubocop
      - name: Run tests
        run: |
          bundle exec ruby test/all.rb
      - name: Execute rubocop
        run: |
          bundle exec rubocop
